debug_make:
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSACA_WERROR=ON ..
        - make
        - ./sacabench/sacabench demo
debug_make_check:
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSACA_WERROR=ON ..
        - make check
release_make:
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release -DSACA_WERROR=ON ..
        - make
        - ./sacabench/sacabench demo
release_make_check:
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release -DSACA_WERROR=ON ..
        - make check
